### ISSUE TITLE
картинки

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#15]
вернуть картинкам углы, по высоте пусть будут 400 пикселей. Левую картинку с текстом подвинуть ближе к левому краю, правые к правому.
на фон в этом блоке примеряйте вот эту картинку 
![- -1](https://cloud.githubusercontent.com/assets/11739563/9562640/1598708c-4e7a-11e5-896c-0edde87e7ca0.jpg)

![image](https://cloud.githubusercontent.com/assets/11739563/9562616/59154836-4e79-11e5-8643-b5bf3910a186.png)

**Comment by dadakax** [comment]
не нужні углі картинкам
и они не должны быть большими, там текста мало
фон можно попробовать поменять, но если ставить этот фон, то картинки с блоков можно вообще убрать наверное

**Comment by dadakax** [comment]
углы не нужны, потому что у нас все круглое

**Comment by olleskiv** [comment]
эту картинку предлагаю просто заокруглить углы, но не кругами

А на счет фона и картинки - пусть будет и то и то, я видела не раз такой прием

Мне интересно, как это будет выглядеть, сейчас там пустовато

**Comment by dadakax** [comment]
нет, должны быть круги, у нас везде круги, надо соблюдать
слишком много картинок будет на фоне
там следующие два блока со стасом на фоне
надо их как-то разбавлять
может блок тренер всунуть под блок кому?

**Comment by olleskiv** [comment]
может лучше насичену программу? Количество текста в лендинге лучше увеличивать сверху-вниз. У тренера слишком много слов

**Comment by dadakax** [comment]
можно
