### ISSUE TITLE
блок с формой

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/charisma#17]
![image](https://cloud.githubusercontent.com/assets/8439283/9562834/46e66abc-4e80-11e5-9cde-a9da2ec5e174.png)
больше шрифт в выделенных надписях,
валидация формы ( оба поля обязательны, валидация имейла)
убрать кнопку записаться сверху

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/9564550/4f0673d0-4eb3-11e5-92ea-9c74c442e4a5.png)
наверное "поспіши зареєструватися" должно быть
и при валидации сообщения об ошибке не выводятся

**Comment by nikolayr1** [comment]
Даш, там красное поле становится если ты неправильно поля заполнил. А если все тип-топ то появляется сообщение "вы успешно зарегались". нет времени разбираться как сделать сообщение о неправильно заполненых полях
