### ISSUE TITLE
блок программа

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/charisma#20]
![image](https://cloud.githubusercontent.com/assets/8439283/9562944/b4bfe5c0-4e82-11e5-841f-df6c2982fe13.png)
лагает параллакс (сделать другой или попробовать сжать картинку)
отступ между элементами списка margin: 10px 0
надпись "та инше" курсивом чуть пониже пикселей на 25 и выравнивание справа

**Comment by nikolayr1** [comment]
та інше допилил в список - так всегда делают в литературе
