### ISSUE TITLE
Блоки для бизнеса и для личной жизни

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/charisma#21]
вернуть ширину 100%
у заголовков ("Кар'єрний ріст", и т.д) text-transform uppercase, размер шрифта 35
размер шрифта у элементов списка 25рх
хуверы для фоток прикольные сделать

**Comment by dadakax** [comment]
ШРИФТЫ!!!

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/9564566/40a38c28-4eb4-11e5-9f90-4bc6c0d5b4ab.png)
картинку по центру

**Comment by dadakax** [comment]
или картинка по центру

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/9566536/13ac5c46-4f12-11e5-8af2-65893c6607e4.png)
между 700 с чем-то и 992 ничего не поменялось

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/9566783/6caa68a4-4f23-11e5-9698-379d2bc0e63a.png)
давайте такую ширину оставим

**Comment by nikolayr1** [comment]
поправил отступ розвиток
![image](https://cloud.githubusercontent.com/assets/11279857/9566798/d1599db0-4f23-11e5-8bae-a8bbd30be608.png)
