### ISSUE TITLE
первый блок

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/charisma#23]
сделать параллакс
кнопку записаться выделить
background position center

**Comment by olleskiv** [comment]
цвет кнопки #FD4223

**Comment by nikolayr1** [comment]
так сойдет?

**Comment by dadakax** [comment]
нормас, только поставь background position center, а то чуваки справа обрезаются, несправедливость

**Comment by Wilvarin** [comment]
но это край картинки.

**Comment by dadakax** [comment]
край картинки? 
![image](https://cloud.githubusercontent.com/assets/8439283/9567012/49d2819e-4f24-11e5-8f67-2cb90279d5d8.png)

**Comment by Wilvarin** [comment]
вот это поворот. в задаче не уточнилось и я подумал что на декстопе они обрезаются.
