### ISSUE TITLE
заменить фотографию на развитие 

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#33]
http://www.soc-ecologia.ru/wp-content/uploads/2013/03/%D1%80%D0%B0%D0%B7%D0%B2%D0%B8%D1%82%D0%B8%D0%B5-%D1%87%D0%B5%D0%BB%D0%BE%D0%B2%D0%B5%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE%D1%82%D0%B5%D0%BD%D1%86%D0%B8%D0%B0%D0%BB%D0%B0.jpg

**Comment by dadakax** [comment]
сделай фотку квадратной пожалуйста, чтоб она круглой біла потом нормально

**Comment by olleskiv** [comment]
переиграла 
![1317880177_1235315133_obu4enie](https://cloud.githubusercontent.com/assets/11739563/9563706/e892e1be-4e95-11e5-9f40-ba47ad281d5c.jpg)

**Comment by dadakax** [comment]
на фтп должен быть олин последний вариант
