### ISSUE TITLE
Блок бонусы

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/charisma#42]
![image](https://cloud.githubusercontent.com/assets/8439283/9566076/ed0639e6-4efc-11e5-9468-7c00e7a62a8a.png)
![image](https://cloud.githubusercontent.com/assets/8439283/9566085/329833ec-4efd-11e5-816c-41affcbc2b34.png)
иконки должны быть внутри блоков (padding-left 40px и будет норм)

вернуть нумерованный список
выравнивание кнопки слева
ну и вернуть кнопки соц сетей наверное

**Comment by nikolayr1** [comment]
кнопки соц сетей раскоментим перед релизом. сейчас они замедляют процесс верстки
