### ISSUE TITLE
таймер

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/charisma#43]
![image](https://cloud.githubusercontent.com/assets/8439283/9566104/1b25ff68-4efe-11e5-8f30-b6ded9da8b13.png)
таймер сломался (хром)

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/9566364/a9940bb8-4f13-11e5-8abb-c73c621899b9.png)
