### ISSUE TITLE
Кнопки

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#53]
Все кнопки должны быть в одном стиле. Изменяем сначала кнопки "регистрация" и "Детальней" , потом все остальные кнопки приводим к такому же стилю (только цвета оставляем, как сейчас)

Что изменить или добавить: font-size: 20px; letter-spacing: 1px; text-transform:uppercase;

![image](https://cloud.githubusercontent.com/assets/11739563/9598312/e1ccd908-5092-11e5-8454-dbf2264ea9fa.png)

**Comment by nikolayr1** [comment]
так приятно когда за тебя стили уже написала заботливый дизайнер)
