### ISSUE TITLE
Заголовки второго уровня

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#57]
(заголовки подтем) Все заголовки второго уровня должны быть в одного размера: font-size: 30 px;
![image](https://cloud.githubusercontent.com/assets/11739563/9598884/fd517a4e-5097-11e5-9b72-fe56d5d738bb.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9598887/03f2193a-5098-11e5-9867-a92a52713a95.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9598892/0aaea11c-5098-11e5-8a6d-eeffb845f7e2.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9598902/143aca94-5098-11e5-90ae-f9e90e6049bb.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9598912/22c84cc6-5098-11e5-947a-06b4a30760ee.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9598906/1c3b93fe-5098-11e5-94fa-394d6737a1aa.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9598918/2c9d15a6-5098-11e5-9391-90cb0ed11d00.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9598924/456b8ab8-5098-11e5-9959-0ceadded1b79.png)

**Comment by olleskiv** [comment]
и без апперкейса. Обычным шрифто с одной заглавной и остальными строчными

**Comment by olleskiv** [comment]
Ну и какого хрена закрыта задача? 
В документе совершенно ничего не сделано

![image](https://cloud.githubusercontent.com/assets/11739563/9614966/e29dfc3e-50fd-11e5-91e1-b9904471753e.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9614978/f34e9e94-50fd-11e5-9262-6ae127b9c782.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9614993/08c5d350-50fe-11e5-8251-51fc35b7081f.png)

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/9615846/dbf7e058-510b-11e5-8053-e78ee32d5ac5.png)
30 - это много 25 - самое то, согласна?

**Comment by olleskiv** [comment]
согласна
