### ISSUE TITLE
убрать лишние анимации

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/charisma#62]

**Comment by olleskiv** [comment]
"бутерброды" точно нужно везде убрать. Они прикольные, но в данном случае слишком мелькают
![image](https://cloud.githubusercontent.com/assets/11739563/9615101/cdf24f28-50fe-11e5-852a-0ae02c471c87.png)

**Comment by nikolayr1** [comment]
ну и что же тогда останется?
только выкатывание кружочков?

**Comment by nikolayr1** [comment]
ладно ладно. ты же дизайнер

**Comment by olleskiv** [comment]
Сделай, чтобы весь текст одновременно выезжал, а не запиливался по строкам.
