### ISSUE TITLE
убрать серую обводку

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#66]
![image](https://cloud.githubusercontent.com/assets/11739563/9615238/ae95dc8e-50ff-11e5-9e91-c2bd3988aa7f.png)

**Comment by nikolayr1** [comment]
обводку чего? картинки или текста?

**Comment by nikolayr1** [comment]
если ты про буквы то они хуевые без 1px тени

**Comment by nikolayr1** [comment]
нечитабельные

**Comment by olleskiv** [comment]
убрать точно, мы потом придумаем лучший способ их выделить. В современном мире обводка текста - это моветон
