### ISSUE TITLE
Заголовок сделать в два рядка

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#69]
первій заголовок разделить на два рядка следующим образом

Як розвинути
свою харизму

и  второй так 

Безкоштовний вебінар
по розвитку комунікативних здібностей

**Comment by olleskiv** [comment]
Хватит просто так закрывать задачи 
![image](https://cloud.githubusercontent.com/assets/11739563/9698980/349153ba-53d8-11e5-834b-4cec73c7a512.png)

**Comment by nikolayr1** [comment]
буду прикреплять скрины. это у тебя наверное кеш был не почищен.
![image](https://cloud.githubusercontent.com/assets/11279857/9831820/eaeb8c22-5976-11e5-9b0b-d2d7ceba0ddc.png)
