### ISSUE TITLE
Одинаковые отступы

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#70]
Уже наверно в третий раз пишу. У всех блоков сверху и снизу должны быть одинаковые отступы. 65 пикселей будет в самый раз 
![image](https://cloud.githubusercontent.com/assets/11739563/9668180/d32d5e98-5288-11e5-9e64-85ab2ff116e5.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9668187/da9ebec4-5288-11e5-8708-510dcef0c663.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9668190/e01ed186-5288-11e5-804f-3685e8243a8e.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9668192/e6341298-5288-11e5-8f47-4e337b27e04e.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9668199/ec2d167c-5288-11e5-8851-2c3de84eb237.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9668207/f62293d2-5288-11e5-923f-9978d06b2a04.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9668218/02a1f0b2-5289-11e5-9f6b-4d2c29324018.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9668223/096388de-5289-11e5-8347-feb047f01635.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9668231/0f240050-5289-11e5-8501-dc5eddf19d76.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9668243/1447ea38-5289-11e5-862b-c47ede4a930b.png)

![image](https://cloud.githubusercontent.com/assets/11739563/9668211/fb7ac32c-5288-11e5-81bf-f8b29ca1b0a4.png)

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/9831855/8d53c5e6-5978-11e5-9af1-2410ca2af5f7.png)
![image](https://cloud.githubusercontent.com/assets/11279857/9831856/96454058-5978-11e5-9576-283cd800d556.png)
![image](https://cloud.githubusercontent.com/assets/11279857/9831858/a10631f0-5978-11e5-92bc-7e20a438955d.png)
![image](https://cloud.githubusercontent.com/assets/11279857/9831861/a5d976c4-5978-11e5-9a12-17c58163c019.png)
![image](https://cloud.githubusercontent.com/assets/11279857/9831862/abf3df54-5978-11e5-8739-2f057fb9cc4e.png)
![image](https://cloud.githubusercontent.com/assets/11279857/9831864/b199ab3c-5978-11e5-8892-a694ea6161c4.png)
