### ISSUE TITLE
футер

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#71]
убрать болд, фонт-сайз 11
![image](https://cloud.githubusercontent.com/assets/11739563/9668323/9832d6b4-5289-11e5-9241-4dae00d2c522.png)

**Comment by olleskiv** [comment]
Коля,  это слишком большой шрифт. Информация в футере не должна быть навязчивой!
![image](https://cloud.githubusercontent.com/assets/11739563/9698990/86b81a48-53d8-11e5-9507-6c990dbcd287.png)

**Comment by nikolayr1** [comment]
сорян. убрал, но забыл про этот медиа запрос.
