### ISSUE TITLE
таймер

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#72]
"днів" со строчной буквы 
![image](https://cloud.githubusercontent.com/assets/11739563/9668366/c53eae9e-5289-11e5-911a-d79121e9098e.png)

**Comment by olleskiv** [comment]
![image](https://cloud.githubusercontent.com/assets/11739563/9699017/d13760fa-53d9-11e5-8c6c-48f7f7dc211c.png)

**Comment by nikolayr1** [comment]
кеш

**Comment by nikolayr1** [comment]
я кое-что понял. у тебя был не почищен кеш. эти задачи сделаны) буду прикреплять скрины кароч.
![image](https://cloud.githubusercontent.com/assets/11279857/9831821/0f2c28a8-5977-11e5-9b2e-03028fa2060d.png)
