### ISSUE TITLE
Поровнять иконки по центру

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#73]
![image](https://cloud.githubusercontent.com/assets/11739563/9668519/a2f8e2b8-528a-11e5-8136-ccb7a08b71dd.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9668527/a867e1cc-528a-11e5-9145-2dbe1e70cf45.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9668534/b15a4d7e-528a-11e5-9936-81e959248a8d.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9668538/b9b19a68-528a-11e5-9a30-f201648cfdfc.png)

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/9831960/59f9ee2e-597c-11e5-907d-33f574327f55.png)
