### ISSUE TITLE
Заголовок второго уровня

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#76]
Все-таки 28 пикс лучше выглядят, чем 25. Поэтому поставить 28 пикс размер ко всем заголовкам второго уровня, а также расстояние от заголовка до контента 30 пикс. Должно бытьь так 
![image](https://cloud.githubusercontent.com/assets/11739563/9670934/e25b41b4-5297-11e5-8c80-b69913943269.png)

**Comment by olleskiv** [comment]
пока писала ишью, уже и шрифты поменяли)

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/9831908/6476d044-597a-11e5-920f-f5df02936617.png)

**Comment by nikolayr1** [comment]
в блоке бонусов font-size: 25px; margin-bottom: 10px; там лучше так
