### ISSUE TITLE
кнопка регистрации

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#77]
заменить надпись на кнопке на "надіслати"
![image](https://cloud.githubusercontent.com/assets/11739563/9670277/69971a9e-5294-11e5-9c34-577b6cf616c8.png)

**Comment by nikolayr1** [comment]
Стас сказал, что пользователи тупые и нужно одинаковые кнопки

**Comment by nikolayr1** [comment]
Приєднуйся!
