### ISSUE TITLE
убрать grayscale при наведении

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#80]
на всех фотографиях 
![image](https://cloud.githubusercontent.com/assets/11739563/9671321/c2eef6a6-529a-11e5-96c9-3550bf1fee4b.png)

**Comment by nikolayr1** [comment]
нам нужны эффекты при наведении

**Comment by olleskiv** [comment]
Сделанм что-то, но не чб э. Поставлю задание придумать эффекты принаведении

**Comment by nikolayr1** [comment]
поставил серпию
