### ISSUE TITLE
в мобильной версии поменять цвет футера

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/charisma#81]
![wp_ss_20150904_0004](https://cloud.githubusercontent.com/assets/11739563/9681199/dfe8a6f2-5304-11e5-8b01-d9accd50740b.png)

**Comment by nikolayr1** [comment]
![screen shot 2015-09-04 at 13 02 41](https://cloud.githubusercontent.com/assets/11279857/9681243/ae27ddbe-530d-11e5-8a7e-9acb76135805.png)
у меня все норм. не знаю почему цвет футера вообще может меняться

**Comment by olleskiv** [comment]
У меня интернет эксплорер на телефоне)) это все объясняет?)

**Comment by nikolayr1** [comment]
пофиг на футер в эксплорере)
